rdb1:
  image: kallqvist/rethinkdb-cluster
  ports:
    - 8080:8080
  environment:
    JOIN: rdb1
  volumes:
    - ./data/rdb01:/data

rdb2:
  image: kallqvist/rethinkdb-cluster
  links:
    - rdb1
  environment:
    JOIN: rdb1
  volumes:
    - ./data/rdb02:/data
