rdb1:
  image: kallqvist/rethinkdb-cluster
  ports:
    - 8080:8080
  volumes:
    - ./data/rdb01:/data

rdb2:
  image: kallqvist/rethinkdb-cluster
  links:
    - rdb1
  environment:
    JOIN: rdb1
  ports:
    - 8081:8080
  volumes:
    - ./data/rdb02:/data

rdb3:
  image: kallqvist/rethinkdb-cluster
  links:
    - rdb1
  environment:
    JOIN: rdb1
  ports:
    - 8082:8080
  volumes:
    - ./data/rdb03:/data
